PRQL/pyprql

noxfile.py
poetry.lock
pyproject.toml
pyprql/cli/cli.py
pyprql/lang/prql.lark
pyprql/lang/prql.py
tests/test_grammar.py

- feat(prql.py): adds grammar for to
- fix(prql.parl): add filename parameter
- fix(prql.lark): support extensions for to statement
- test(test_grammar.py): add unit tests for to statements
- feat(prql.py): parse to statements
- feat(cli.py): support cli saving to csv
- feat(*): support saving to tsv
- feat(cli.py): support reading from tsvs
- docs(cli.py): document connect_str properly
- build(pyproject.toml): specify numpy version

Support writing to CSVs/TSVs

---

.gitignore
.readthedocs.yaml
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/assets.md
docs/changelog.md
docs/cli.md
docs/cli_class.md
docs/coc.md
docs/completer.md
docs/conf.py
docs/contributing.md
docs/index.md
docs/lang.md
docs/lexer.md
docs/pyprql.md
docs/readme.md
docs/requirements.txt
docs/styler.md
docs/tests.md
noxfile.py
pyproject.toml
pyprql/assets/cli_usage.txt
pyprql/cli/PRQLCompleter.py
pyprql/cli/PRQLLexer.py
pyprql/cli/PRQLStyle.py
pyprql/cli/cli.py
pyprql/lang/prql.py

- build(.gitignore): ignore vim session files
- docs(*): provide docstrings throughout
- docs(docs): add Sphinx support
- refactor(*): apply various lints to build docs
- docs(README.md): get those badges
- docs(*): correct urls

Get sphinx build running

---

docs/test_employee_examples.md
docs/test_factbook_examples.md
docs/test_functions.md
docs/test_grammar.md
docs/test_prql_util_functions.md
docs/test_sql_generator.md
docs/test_stdlib.md
docs/tests.md
noxfile.py
poetry.lock
pyproject.toml
tests/test_employee_examples.py
tests/test_factbook_examples.py
tests/test_functions.py
tests/test_grammar.py
tests/test_prql_util_functions.py
tests/test_sql_generator.py
tests/test_stdlib.py

- ci(noxfile.py): add tests to lints
- refactor(tests): apply lints
- docs(tests): document tests
- docs(docs): add tests to the sphinx build

Add documentation for testing

---

pyprql/cli/cli.py
pyprql/magic/README.md

Fixes docs

---

pyprql/cli/cli.py
pyprql/magic/README.md

fix:  Fixes docs

---

docs/conf.py

fix: Update docs

---

README.md
poetry.lock
pyproject.toml
pyprql/pandas/__init__.py
pyprql/pandas/prql.py
tests/test_prql_python.py

Merging into official branch before PR to main

Prettier notebook output

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docs/conf.py
docs/magic_implement.md
docs/magic_init.md
noxfile.py
pyproject.toml
pyprql/__init__.py
pyprql/assets/cli_usage.txt
pyprql/cli/PRQLCompleter.py
pyprql/cli/PRQLLexer.py
pyprql/cli/PRQLStyle.py
pyprql/cli/__init__.py
pyprql/cli/cli.py
pyprql/magic/README.md
pyprql/magic/__init__.py

Open-minded on what to use (though let's use one) -- I've been doing `PRQL` for the lang and `prql` for the project. So taken that approach here.

docs: Make capitalization consistent

---

poetry.lock
pyproject.toml
pyprql/magic/README.md
pyprql/magic/prql.py

Thanks a lot to @catherinedevlin for kicking off the extension!
Because of https://github.com/catherinedevlin/ipython-sql/issues/210, it's necessary for us to transition to a fork, but open-minded on what we depend on if things get merged upstream.

build: Transition to ploomber/jupysql

---

pyprql/magic/prql.py

This demonstrates we need tests for the magic...

fix: Add py3.8-compatible typing

---

pyproject.toml
pyprql/__init__.py

Not sure why semantic-release isn't working, so doing manually

chore: Update version to 0.5.11

---

pyproject.toml
pyprql/__init__.py

Me & semantic-release really aren't getting along well...

build: Bump version locally

---

.github/workflows/release.yaml

If this doesn't work, we'll disable the auto-release...

ci: Use PSR action

---

.github/workflows/pull-request.yaml
pyproject.toml

IPython is not supporting python 3.7

fix: fix python versions

---

.github/workflows/pull-request.yaml

No need to test the middle versions, would be an extreme situation where one of those would catch something

ci: Reduce matrix size, upgrade poetry

---

poetry.lock

Dependency conflict between safety & black

revert: #207

---

.github/workflows/release.yaml

ci: fix permission

---

.github/workflows/release.yaml

ci: fix artifact download path

---

poetry.lock
pyprql/tests/conftest.py

chore: bump jupysql from 0.9.0 to 0.10.0

---

poetry.lock

This might fix the greenlet problem

build: Upgrade dependencies

---

.flake8

chore: Remove flake8 config file
